name: Compile ZONA Flutter App

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Configurer Java (Requis pour Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurer Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Installer les dépendances
        run: flutter pub get

      - name: Compiler le fichier APK
        run: flutter build apk --release

      - name: Uploader l'APK généré (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: ZONA-Android-APK
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Compiler le fichier AAB (Pour le Google Play Store)
        run: flutter build appbundle --release

      - name: Uploader l'AAB généré (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: ZONA-Android-AAB
          path: build/app/outputs/bundle/release/app-release.aab